name: Canny Monkey Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77673
title: Travel and Landscape Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbccde'
    - '#b7aaa2'
    - '#9e9189'
    - '#4a4c3e'
    - '#6b7685'
  brandStrength: 0.4527681991457939
  lightness: 0.375
  saturation: 0.9975709340069443
  rhythmicContrast: 0.5062865370418876
purpose: []
